server:
  port: 7076

spring:
  ##Knife4j配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

#日志配置
logging:
  file:
    name: logs/logs
  level:
    com.demo: debug

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: tldzqjysvduqsdybnnldbkksfgpbglcqfhujbqbxbcbgdtabfophxxtdpzmuanqjlqwkqihpujdlsfqbztxwmzrdpglmreshlfkyljizkrvbthwewgpqoendfloxxhclyzdilcepdafzofizibjyslguddpynoahwkszqkggxqyxpggsdcmtufnvbipmrzoakcnyygzdqnpdlzjhgbhihnlbwlbvzjlmfazvnfpdmdesnxqthgedqrcrbdonqxukbyytioprcafttuvpwrpucfmxulvalvkcwfnjmavqgrvzaxqeuthltoxkwiziwadjpihyzwpyotttiyrmmbochmtvjdahnwtovmnqzvsvvtroyjqyefqrqgohrlfrmdivpfgktgzxqvoucejsxbretmqbjspdkgxaviqgkkdhecdvltuxanijbneqmglnlrlhwoyifswczglftjcbaydpfcklqpgtbavhvatwrfrcnftpeqcnokoitvgmrogkxnvo
  # 令牌有效期（默认30分钟）
  expireTime: 30